# Generated by Django 2.2.24 on 2021-07-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20210710_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='app_label',
            field=models.CharField(blank=True, choices=[('compressor', 'compressor'), ('joyous', 'joyous'), ('mptt', 'mptt'), ('publications', 'publications'), ('projects', 'projects'), ('standard', 'standard'), ('eppe', 'eppe'), ('cc', 'cc'), ('fc', 'fc'), ('paleosites', 'paleosites')], max_length=100, null=True),
        ),
    ]
